---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ccengeu/test.cceng.eu/
    - export INCLUDES_DEPLOYPATH=/home/ccengeu/test.cceng.eu/includes/
    - /bin/cp -R .idea $DEPLOYPATH
    - /bin/cp -R form $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp results.php $DEPLOYPATH
    - /bin/cp downloads.inc.php $INCLUDES_DEPLOYPATH
    - /bin/cp queries.inc.php $INCLUDES_DEPLOYPATH
